### ISSUE TITLE
ALPACA: Update Specials Prices and Hours

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#212]
Please update the menu prices to all of the menu specials to $8.99

Update Hours to 11am - 9pm

**Comment by codeyash** [comment]
Done

**Comment by grethapouza** [comment]
Today is Tuesday but the hours are not shown for the "Taco Tuesday Special"
and the product states that its unavailable, please review/resolve this.

Best,

Gretha Pouza
*VP Operations*
SAM IT Solutions
p: 919.800.0044  m: 919.890.0543
a: 15100 Weston Parkway #204, Cary, NC 27513
w: www.samitsolutions.com  e: gretha@samitsolutions.com
<https://www.facebook.com/SamAnalytic/>
<https://www.linkedin.com/company/577955?trk=vsrp_companies_cluster_name&trkInfo=VSRPsearchId%3A2978210991481772931150%2CVSRPtargetId%3A577955%2CVSRPcmpt%3Acompanies_cluster>

CONFIDENTIALITY NOTICE: This e-mail message and any attachments are for the
sole use of the intended recipient(s) and may contain proprietary,
confidential, trade secret or privileged information. Any unauthorized
review, use, disclosure or distribution is prohibited and may be a
violation of law. If you are not the intended recipient or a person
responsible for delivering this message to an intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message and any attachments.

**Comment by codeyash** [comment]
Today right now time is 

10:13 AM
Tuesday, 2 May 2017 (GMT-4)
Time in North Carolina, USA

The Deal will open at 11 AM to buy online. If you to open earlier please update time to 8 or 9 AM instead of 11 AM

Special Deal can be buy in the timeslot and can't be booked advanced. This is what special hours mean.
Please correct me if anything else required and I'm doing wrong.

Let me know if you need any more clarification.

**Comment by codeyash** [comment]
Now it's active and we're in the time window.

It's working fine.

Let me know if anything else required here.

**Comment by codeyash** [comment]
Closing. Please reopen or open a new bug if anything else required.
